source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "webrick", "~> 1.7"

# Load the plugin from local path for rapid development without pushing.
group :jekyll_plugins do
  gem "jekyll-resize", :path => '../'
end
