source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "kramdown-parser-gfm", "~> 1.1"  # Required for Jekyll 3.9 (not 3.8 or 4)
gem "webrick", "~> 1.7"  # Ruby 3 support

group :jekyll_plugins do
  gem "jekyll-resize", :path => '../'
end
